prometheus.yaml
A simple Prometheus configuration file to scrape metrics from our services.
global:
scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:

job_name: 'assistant_service'

Scrape metrics from the assistant service endpoint.
kubernetes_sd_configs:

role: endpoints
relabel_configs:

source_labels: [__meta_kubernetes_service_name]
regex: genai-assistant-service
action: keep

source_labels: [__meta_kubernetes_pod_container_name]
regex: assistant
action: keep