apiVersion: batch/v1
kind: Job
metadata:
  name: cv-trainer-job
spec:
  template:
    spec:
      containers:
        - name: cv-trainer-container
          image: your-docker-registry/cv-trainer:latest
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
              ephemeral-storage: "10Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
              ephemeral-storage: "20Gi"
      restartPolicy: Never
  backoffLimit: 4
